name: Production - Deploy via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: self-hosted
    environment: PROD
    env:
      HUGO_BASEURL: https://imeko2026.fel.cvut.cz/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Hugo site
        run: hugo --gc --minify --baseURL "$HUGO_BASEURL"

      - name: Upload via FTP/FTPS
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "
            set ftp:passive-mode on
            set net:max-retries 2
            set net:timeout 20
            set net:reconnect-interval-base 5
            set ftp:ssl-allow yes
            set ftp:ssl-force true
            set ssl:verify-certificate no
            open -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER
            cd /web/
            mirror -R --parallel=2 --verbose public/ ./ 
          "